// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workerdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bill struct {
	ID            uuid.UUID      `json:"id"`
	AccountID     string         `json:"account_id"`
	Currency      string         `json:"currency"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	PeriodStart   time.Time      `json:"period_start"`
	PeriodEnd     time.Time      `json:"period_end"`
	ClosedAt      sql.NullTime   `json:"closed_at"`
	TotalMinor    int64          `json:"total_minor"`
	WorkflowID    string         `json:"workflow_id"`
	WorkflowRunID sql.NullString `json:"workflow_run_id"`
}

type LineItem struct {
	ID             uuid.UUID `json:"id"`
	BillID         uuid.UUID `json:"bill_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	PayloadHash    string    `json:"payload_hash"`
	Description    string    `json:"description"`
	AmountMinor    int64     `json:"amount_minor"`
	CreatedAt      time.Time `json:"created_at"`
}
