// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package workerdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const closeBillByID = `-- name: CloseBillByID :execresult
UPDATE bills
SET status = 'CLOSED', closed_at = COALESCE(closed_at, NOW()), updated_at = NOW()
WHERE id = $1 AND status = 'OPEN'
`

func (q *Queries) CloseBillByID(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, closeBillByID, id)
}

const getBillStatus = `-- name: GetBillStatus :one
SELECT status FROM bills WHERE id = $1
`

func (q *Queries) GetBillStatus(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getBillStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getLineItemByBillAndKey = `-- name: GetLineItemByBillAndKey :one
SELECT id, description, amount_minor, payload_hash, created_at
FROM line_items WHERE bill_id = $1 AND idempotency_key = $2
`

type GetLineItemByBillAndKeyParams struct {
	BillID         uuid.UUID `json:"bill_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

type GetLineItemByBillAndKeyRow struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	AmountMinor int64     `json:"amount_minor"`
	PayloadHash string    `json:"payload_hash"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetLineItemByBillAndKey(ctx context.Context, arg GetLineItemByBillAndKeyParams) (GetLineItemByBillAndKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getLineItemByBillAndKey, arg.BillID, arg.IdempotencyKey)
	var i GetLineItemByBillAndKeyRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.AmountMinor,
		&i.PayloadHash,
		&i.CreatedAt,
	)
	return i, err
}

const incrementBillTotal = `-- name: IncrementBillTotal :one
UPDATE bills
SET total_minor = total_minor + $1, updated_at = NOW()
WHERE id = $2
RETURNING total_minor, updated_at
`

type IncrementBillTotalParams struct {
	Amount int64     `json:"amount"`
	BillID uuid.UUID `json:"bill_id"`
}

type IncrementBillTotalRow struct {
	TotalMinor int64     `json:"total_minor"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) IncrementBillTotal(ctx context.Context, arg IncrementBillTotalParams) (IncrementBillTotalRow, error) {
	row := q.db.QueryRowContext(ctx, incrementBillTotal, arg.Amount, arg.BillID)
	var i IncrementBillTotalRow
	err := row.Scan(&i.TotalMinor, &i.UpdatedAt)
	return i, err
}

const insertLineItemIdempotent = `-- name: InsertLineItemIdempotent :one
INSERT INTO line_items (id, bill_id, idempotency_key, payload_hash, description, amount_minor, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (bill_id, idempotency_key) DO NOTHING
RETURNING id, created_at
`

type InsertLineItemIdempotentParams struct {
	ID             uuid.UUID `json:"id"`
	BillID         uuid.UUID `json:"bill_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	PayloadHash    string    `json:"payload_hash"`
	Description    string    `json:"description"`
	AmountMinor    int64     `json:"amount_minor"`
}

type InsertLineItemIdempotentRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertLineItemIdempotent(ctx context.Context, arg InsertLineItemIdempotentParams) (InsertLineItemIdempotentRow, error) {
	row := q.db.QueryRowContext(ctx, insertLineItemIdempotent,
		arg.ID,
		arg.BillID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.Description,
		arg.AmountMinor,
	)
	var i InsertLineItemIdempotentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const lockBillForUpdate = `-- name: LockBillForUpdate :one

SELECT account_id, currency, status, created_at, updated_at,
       period_start, period_end, closed_at, total_minor
FROM bills WHERE id = $1 FOR UPDATE
`

type LockBillForUpdateRow struct {
	AccountID   string       `json:"account_id"`
	Currency    string       `json:"currency"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	PeriodStart time.Time    `json:"period_start"`
	PeriodEnd   time.Time    `json:"period_end"`
	ClosedAt    sql.NullTime `json:"closed_at"`
	TotalMinor  int64        `json:"total_minor"`
}

// Queries used by the Temporal worker for bill mutations.
// Source of truth for sqlc code generation (see sqlc.yaml at project root).
// Read-only queries used by the API service remain in billing/store.go.
func (q *Queries) LockBillForUpdate(ctx context.Context, id uuid.UUID) (LockBillForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, lockBillForUpdate, id)
	var i LockBillForUpdateRow
	err := row.Scan(
		&i.AccountID,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ClosedAt,
		&i.TotalMinor,
	)
	return i, err
}
